language: python
python:
  - 2.7
addons:
  apt:
    packages:
      - gcc
      - libblas-dev
      - liblapack-dev
      - libatlas-dev
      - gfortran
      - python-numpy
      - python-scipy
      - python-cvxopt
      - aria2
before_install:
  - aria2c -x 10 -k 1M http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.3.tar.gz
  - tar -xf SuiteSparse-4.5.3.tar.gz
  - export CVXOPT_SUITESPARSE_SRC_DIR=$(pwd)/SuiteSparse
script:
  - python setup.py test
